"""Review Model Added

Revision ID: c891e135fd86
Revises: b72b66d0881c
Create Date: 2023-06-28 10:43:11.420085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c891e135fd86'
down_revision = 'b72b66d0881c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
